version: '3.7'

# Define services
services:
  ubxlib_builder:
    image: ubxlib_builder
    build: .
# Note: used to define the environment variable SSH_AUTH_SOCK
# here but for some reason that doesn't work when composing
# on Raspbian, hence moved them to the .env file which _does_ work
    volumes:
      - '/opt/ubxlib_sdks:/home/ubxlib/ubxlib_sdks'
      - '$SSH_AUTH_SOCK:/run/user/keyring/ssh'
    stdin_open: true # docker run -i
    tty: true        # docker run -t
